### PR TITLE
Feature led lib

### PR DESCRIPTION
**Pull request by cu-boulder-robotics**
Added Fast LED Library to be able to control the neopixels from the teensy

### CODE REVIEW

**Review by StudentKyle — APPROVED** [review]
Looks good, but merge other PR (SD lib) first.

**Review by StudentKyle — CHANGES_REQUESTED** [review]
test and merge other PR first

**Comment by StudentKyle** [comment]
ignore it

**Comment by Pandabear1125** [comment]
bruh

**Pull request closed without merging**
